name: lottery-platform-dev-edge

services:
  nginx:
    build:
      context: ../docker
      dockerfile: build/nginx/Dockerfile
    image: lottery-nginx:local
    container_name: lottery-nginx
    restart: unless-stopped
    environment:
      FRONTEND_MODE: ${FRONTEND_MODE:-static}
      FRONTEND_DEV_SERVER: ${FRONTEND_DEV_SERVER:-http://host.docker.internal:9510}
      GATEWAY_SERVER: ${GATEWAY_SERVER:-http://host.docker.internal:9008}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${NGINX_HTTP_PORT:-9010}:80"
    volumes:
      - ../docker/conf/nginx/html:/usr/share/nginx/html:ro
    networks:
      - lottery-net

networks:
  lottery-net:
    driver: bridge
